Ejercicio subido
GAGdelSolar/entregableOctubre pull request #1
Opened 2022-11-11 01:05 UTC by GAGdelSolar

2022-11-14 22:32 UTC, gonzalezvictorjuan commented on teoria.txt
> +¿Qué son las interfaces?
hay algunas sin responder

2022-11-14 22:32 UTC, gonzalezvictorjuan requested changes
terminar de contestar las teoricas

2022-11-14 23:26 UTC, GAGdelSolar commented
Hola Victor! Ahi lo agregue, en realidad lo deje sin contestar xq ya eran las 10 y ademas me parecio justo no ponerlo siendo que para ser sincero aun no lo tengo tan incorporado para explicarlo con mis palabras como hice en las anteriores. De todos modos ahi las complete un poco googleando y otro poco aportando lo que voy entendiendo de estos 2 temas (abstract e interfaz) Gracias!

2022-11-16 12:37 UTC, gonzalezvictorjuan approved these changes

2022-11-16 12:37 UTC, merged